# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

name: iOS

on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:
    branches:
      - main
      - 'releases/**'

jobs:
  macos:
    name: iOS build
    runs-on: macos-latest

    strategy:
      matrix:
        config:
            - { name: "Qt5", pattern: qt5, folder: ios, macosPattern: x, macosFolder: qt }
            - { name: "Qt6", pattern: qt6, folder: ios, macosPattern: qt6, macosFolder: qt6 }

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Install ${{matrix.config.name}}
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git clone https://github.com/mozilla-mobile/qt_ios
          cd qt_ios
          cat ${{matrix.config.pattern}}* > qt_static_ios.tar.gz
          tar xf qt_static_ios.tar.gz
          sudo mv ${{matrix.config.folder}} /opt
          cd ..
          git clone https://github.com/mozilla-mobile/qt_static_macos
          cd qt_static_macos
          cat ${{matrix.config.macosPattern}}* > qt_static.tar.gz
          tar xf qt_static.tar.gz
          sudo mv ${{matrix.config.macosFolder}} /opt
          cd ..

      - name: Generating glean samples
        shell: bash
        run: |
          pip3 install -r requirements.txt
          python3 scripts/utils/generate_glean.py

      - name: Importing translation files
        shell: bash
        run: |
          export PATH=/opt/${{matrix.config.folder}}/bin:/opt/${{matrix.config.macosFolder}}/bin:$PATH
          git submodule update --remote --depth 1 i18n
          python3 scripts/utils/import_languages.py -m

      - name: Switch to newest go version
        shell: bash
        run: |
          rm /usr/local/bin/go
          rm /usr/local/bin/gofmt
          brew install go

      - name: Configuring the build
        shell: bash
        run: |
          export QT_IOS_BIN=/opt/${{matrix.config.folder}}/bin
          SHORTVERSION=$(cat version.pri | grep VERSION | grep defined | cut -d= -f2 | tr -d \ )
          FULLVERSION=$(echo $SHORTVERSION | cut -d. -f1).$(date +"%Y%m%d%H%M")
          cat > xcode.xconfig << EOF
          DEVELOPMENT_TEAM = 43AQ936H96
          GROUP_ID_MACOS = group.org.mozilla.macos.Guardian
          APP_ID_MACOS = org.mozilla.macos.FirefoxVPN
          NETEXT_ID_MACOS = org.mozilla.macos.FirefoxVPN.network-extension
          LOGIN_ID_MACOS = org.mozilla.macos.FirefoxVPN.login-item
          GROUP_ID_IOS = group.org.mozilla.ios.Guardian
          APP_ID_IOS = org.mozilla.ios.FirefoxVPN
          NETEXT_ID_IOS = org.mozilla.ios.FirefoxVPN.network-extension
          EOF
          ./scripts/macos/apple_compile.sh ios

      - name: Prebuilding Qt
        shell: bach
        run: |
          make -f MozillaVPN.xcodeproj/qt_makeqmake.mak
          make -f MozillaVPN.xcodeproj/qt_preprocess.mak

      - name: Compiling
        shell: bash
        run: xcodebuild build CODE_SIGN_IDENTITY="" CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO -project MozillaVPN.xcodeproj
